### ISSUE TITLE
Docker based Upgrade 0.6.0 - 0.7.0

### ISSUE THREAD

**Issue by mat-l** [superseriousbusiness/gotosocial#1515]
Dear all,
I wanted to upgrade from 0.6.0 to the latest 0.7.0 version in my Docker based deplyoment.

I am running the following docker commands:
```
docker stop gotosocial
docker rm gotosocial
docker pull superseriousbusiness/gotosocial:latest
docker-compose up -d
```

As a result I am seeing "502 Bad Gateway nginx/1.23.3".
I am not sure, but my Nginx proxy container does not show any special negative points:
```
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/dist/_colors.css HTTP/2.0" 200 1550 "https://tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/dist/base.css HTTP/2.0" 200 4349 "https://tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET / HTTP/2.0" 200 3415 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/logo.png HTTP/2.0" 200 27204 "https://tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/mastodon.svg HTTP/2.0" 200 765 "https://tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/tusky.svg HTTP/2.0" 200 7157 "https://tld/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:44 +0000] "GET /assets/fonts/noto-sans-v27-latin-regular.woff2 HTTP/2.0" 200 12860 "https://tld/assets/dist/base.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | tld 163.116.178.124 - - [17/Feb/2023:13:54:45 +0000] "GET /assets/fonts/noto-sans-v27-latin-700.woff2 HTTP/2.0" 200 12684 "https://tld/assets/dist/base.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.6:8080"
nginx.1     | cloud.mnethome.de 163.116.178.124 - - [17/Feb/2023:13:54:48 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.8:80"
nginx.1     | cloud.mnethome.de 163.116.178.124 - - [17/Feb/2023:13:54:49 +0000] "POST /apps/text/session/sync HTTP/2.0" 200 238 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0" "172.20.0.8:80"
```

After upgrading from gotosocial 0.6.0 to 0.7.0 the gotosocial container shows the following printouts:
```
timestamp="17/02/2023 13:51:43.398" func=bundb.sqliteConn level=INFO msg="connected to SQLITE database with address file:/gotosocial/storage/sqlite.db?_txlock=immediate"
timestamp="17/02/2023 13:51:43.400" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma journal_mode set to wal"
timestamp="17/02/2023 13:51:43.400" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma synchronous set to 1"
timestamp="17/02/2023 13:51:43.400" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma cache_size set to -8192"
timestamp="17/02/2023 13:51:43.400" func=bundb.sqlitePragmas level=INFO msg="sqlite pragma busy_timeout set to 300000"
timestamp="17/02/2023 13:51:43.405" func=bundb.doMigration level=INFO msg="there are no new migrations to run"
timestamp="17/02/2023 13:51:43.405" func=bundb.(*adminDB).CreateInstanceAccount level=INFO msg="instance account tld already exists"
timestamp="17/02/2023 13:51:43.405" func=bundb.(*adminDB).CreateInstanceInstance level=INFO msg="instance entry already exists"
```

My docker-compose file looks like this:
```
version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:0.7.0
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
      - default
    environment:
      GTS_HOST: tld
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      #GTS_LETSENCRYPT_EMAIL_ADDRESS: "tobias.masiak@mnethome.de"
      VIRTUAL_HOST: tld
      VIRTUAL_PORT: 8080
      LETSENCRYPT_HOST: tld
      LETSENCRYPT_EMAIL: my mail adress
      GTS_TRUSTED_PROXIES: "172.20.0.6"
    ports:
      - "8080:8080"
      #- "88:80"
    volumes:
      - /gotosocial/data:/gotosocial/storage
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
  default:
    external:
      name: nextcloud_proxy-tier
```

Any ideas what is going wrong here?
