### ISSUE TITLE
[bug] Docker compose not support timezone env

### ISSUE THREAD

**Issue by eallion** [superseriousbusiness/gotosocial#2045]
### Describe the bug with a clear and concise description of what the bug is.

Docker compose not support timezone env

### What's your GoToSocial Version?

0.10.1-SNAPSHOT 

### GoToSocial Arch

amd64 docker

### What happened?

I live in UTC+8, when i post a toot to Gotosocial through the app, time is always 8 hours slow.

### What you expected to happen?

Docker support zimezone env
We can set it in the `docker-compose.yml` or in the `Dockerfile`
There's a better way to use like some other containers:

```yml
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
```

### How to reproduce it?

Docker run an instance in other timezone.

### Anything else we need to know?

I tried to set the local time of the server, but it didn't take effect for this container.
