### ISSUE TITLE
[bug] I can't edit the toots

### ISSUE THREAD

**Issue by eallion** [superseriousbusiness/gotosocial#2072]
### Describe the bug with a clear and concise description of what the bug is.

I running a Docker container istance, I can't edit the toots form any apps.

```
Failed to load the status source from the server.
```

Here's my docker-compose.yml:
```
version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:snapshot
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    environment:
      - GTS_HOST=m.eallion.com
      - GTS_ACCOUNT_DOMAIN=eallion.com
      - GTS_DB_TYPE=sqlite
      - GTS_DB_ADDRESS=/gotosocial/storage/sqlite.db
      - GTS_LETSENCRYPT_ENABLED=false
      - GTS_ACCOUNTS_ALLOW_CUSTOM_CSS=true
      - TZ=Asia/Shanghai
    ports:
      - "8087:8080"
    volumes:
      - ./gotosocial/data:/gotosocial/storage
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
```

Screnshot

![Screenshot_2023-08-06-14-12-28-698_com keylesspalace tusky](https://github.com/superseriousbusiness/gotosocial/assets/1698841/57642e52-60d3-4e5e-b08e-cbffcf48cb64)

### What's your GoToSocial Version?

0.10.1-snapshot

### GoToSocial Arch

arm64 Docker
