### ISSUE TITLE
Move gotosocial from a vps to another

### ISSUE THREAD

**Issue by huabin** [superseriousbusiness/gotosocial#2197]
Hello guys,

I need to move gotosocial to another vps, and I run gotosocial via Docker compose like following

```
version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gomso
    user: root:root
    networks:
      - gotosocial
    environment:
      GTS_HOST: gomso.com
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
    ports:
      - "8080:8080"
    volumes:
      - ~/gomso/data:/gotosocial/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
```

I didn't find `sqlite.db` and media files in local folder `~/gomso/data`. Any ideas? Thank you so much.
