### ISSUE TITLE
How to update the domain name for gotosocial?

### ISSUE THREAD

**Issue by huabin** [superseriousbusiness/gotosocial#2450]
Hello everyone,

I apologize for any inconvenience.

I've been operating the gotosocial node for several months now and have accumulated some data. Initially, I ran it under port 8080 using docker-compose.yaml and utilized an nginx proxy to set the domain name as follows:

docker-compose.yaml

```
services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: tcm
    user: root:root
    networks:
      - gotosocial
    environment:
      GTS_HOST: a.com
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/tcm/data:/gotosocial/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
```

nginx

```
server {
    listen  80;
    server_name a.com;
    location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header HOST $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://127.0.0.1:8080;
            proxy_redirect off;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Now, I need to change its domain name to `b.com`. I deleted the old docker container and updated both nginx and docker-compose.yaml

docker-compose.yaml

```
services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: tcm
    user: root:root
    networks:
      - gotosocial
    environment:
      GTS_HOST: b.com
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/tcm/data:/gotosocial/storage
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
```

nginx

```
server {
    listen  80;
    server_name b.com;
    location / {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header HOST $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://127.0.0.1:8080;
            proxy_redirect off;
            proxy_set_header X-Real-PORT $remote_port;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

I've run a new docker container based on the above configuration files and the old data. However, there are some issues:

- I can visit the website via the new domain name `b.com`, but none of the assets, such as images in the posts, are displayed.
- There was only one user on `a.com`, but after changing the domain name to `b.com`, the content displayed on the home page changed from `home to 1 user who posted 28 statuses, federating with 2 other instances.` to `home to 2 users who posted 28 statuses, federating with 2 other instances.`

I would appreciate guidance on the correct way to change a domain name. Thank you so much.
