### ISSUE TITLE
[bug] Instance Not Federating

### ISSUE THREAD

**Issue by willowbit** [superseriousbusiness/gotosocial#2573]
### Describe the bug with a clear and concise description of what the bug is.

My self-hosted instance does not federate, and follow requests pend with no request showing up. My user @willa@social.magland.org, does appear on other instances. GoToSocial is running behind an NGINX reverse proxy.

**GoToSocial Config**
```
log-level: "info"
log-db-queries: false
log-client-ip: true
log-timestamp-format: "02/01/2006 15:04:05.000"
application-name: "gotosocial"
landing-page-user: ""
host: "social.magland.org"
account-domain: "social.magland.org"
protocol: "https"
bind-address: "127.0.0.1"
port: 3000
trusted-proxies:
  - "127.0.0.1/32"
  - "::1"
db-type: "sqlite"
db-address: "sqlite.db"
db-port: 5432
db-user: ""
db-password: ""
db-database: "gotosocial"
db-tls-mode: "disable"
db-tls-ca-cert: ""
db-max-open-conns-multiplier: 8
db-sqlite-journal-mode: "WAL"
db-sqlite-synchronous: "NORMAL"
db-sqlite-cache-size: "8MiB"
db-sqlite-busy-timeout: "30m"
cache:
  memory-target: "100MiB"
web-template-base-dir: "./web/template/"
web-asset-base-dir: "./web/assets/"
instance-languages: []
instance-federation-mode: "blocklist"
instance-expose-peers: false
instance-expose-suspended: false
instance-expose-suspended-web: false
instance-expose-public-timeline: false
instance-deliver-to-shared-inboxes: true
instance-inject-mastodon-version: false
accounts-registration-open: false
accounts-approval-required: true
accounts-reason-required: true
accounts-allow-custom-css: false
accounts-custom-css-length: 10000
media-image-max-size: 10485760
media-video-max-size: 41943040
media-description-min-chars: 0
media-description-max-chars: 500
media-emoji-local-max-size: 51200
media-emoji-remote-max-size: 102400
media-remote-cache-days: 7
media-cleanup-from: "00:00"
media-cleanup-every: "24h"
storage-backend: "local"
storage-local-base-path: "/gotosocial/storage"
storage-s3-endpoint: ""
storage-s3-proxy: false
storage-s3-use-ssl: true
storage-s3-access-key: ""
storage-s3-secret-key: ""
storage-s3-bucket: ""
statuses-max-chars: 5000
statuses-cw-max-chars: 100
statuses-poll-max-options: 6
statuses-poll-option-max-chars: 50
statuses-media-max-files: 6
letsencrypt-enabled: false
letsencrypt-port: 80
letsencrypt-cert-dir: "/gotosocial/storage/certs"
letsencrypt-email-address: ""
tls-certificate-chain: ""
tls-certificate-key: ""
oidc-enabled: false
oidc-idp-name: ""
oidc-skip-verification: false
oidc-issuer: ""
oidc-client-id: ""
oidc-client-secret: ""
oidc-scopes:
  - "openid"
  - "email"
  - "profile"
  - "groups"
oidc-link-existing: false
oidc-admin-groups: []
smtp-host: ""
smtp-port: 0
smtp-username: ""
smtp-password: ""
smtp-from: ""
smtp-disclose-recipients: false
syslog-enabled: false
syslog-protocol: "udp"
syslog-address: "localhost:514"
request-id-header: "X-Request-Id"
tracing-enabled: false
tracing-transport: "grpc"
tracing-endpoint: ""
tracing-insecure-transport: false
metrics-enabled: false
metrics-auth-enabled: false
metrics-auth-username: ""
metrics-auth-password: ""
http-client:
  timeout: "10s"
  allow-ips: []
  block-ips: []
  tls-insecure-skip-verify: false
advanced-cookies-samesite: "lax"
advanced-rate-limit-requests: 300
advanced-rate-limit-exceptions: []
advanced-throttling-multiplier: 8
advanced-throttling-retry-after: "30s"
advanced-sender-multiplier: 2
advanced-csp-extra-uris: []
```
**Nginx Reverse Proxy**
```
server {
  server_name social.magland.org;
  location / {
    proxy_pass http://127.0.0.1:3000;
    proxy_set_header Host $host;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
  client_max_body_size 40M;

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/social.magland.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/social.magland.org/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}

server {
    if ($host = social.magland.org) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
    if ($host = http://willa.magland.org) {
    	return 301 https://$host$request_uri;
    }


  listen 80;
  listen [::]:80;
  server_name social.magland.org;
    return 404; # managed by Certbot
}
```

### What's your GoToSocial Version?

v0.13.1

### GoToSocial Arch

amd64 Binary

### What happened?

Followed installation instructions for GoToSocial and setting up with a reverse proxy.

### What you expected to happen?

Federation with mastodon.social & other mastodon instances

### How to reproduce it?

1. Go to activity pub instance
2. Follow @willa@social.magland.org
3. Request pends

### Anything else we need to know?

In the console I see:
```
timestamp="26/01/2024 03:41:08.184" func=bundb.(*adminDB).CreateInstanceAccount level=INFO msg="instance account social.magland.org already exists"
timestamp="26/01/2024 03:41:08.185" func=log.Infof level=INFO msg="instance entry already exists"
```
when I start the server.
