### ISSUE TITLE
[bug] Can't access settings panels with OIDC

### ISSUE THREAD

**Issue by bachrc** [superseriousbusiness/gotosocial#2719]
### Describe the bug with a clear and concise description of what the bug is.

I use Authelia which I configured with Gotosocial. Creating an account works, posts, etc.

But when i reach to the `/admin` endpoint, or the `/settings`, i have a page which tolds me:

`400: Waiting for callback, but no ?code= provided in url.`

And in the text field, when I click submit so "redirect to the panel", i do not get redirected.

### What's your GoToSocial Version?

v0.13.3

### GoToSocial Arch

arm64 Docker

### What happened?

I installed the Gotosocial docker image, behind caddy.

### Anything else we need to know?

My caddy config

```Caddyfile
social.example.net {
	# Optional, but recommended, compress the traffic using proper protocols
	encode zstd gzip

	# The actual proxy configuration to port 8080 (unless you've chosen another port number)
	reverse_proxy * 172.28.5.15:8080 {
		# Flush immediatly, to prevent buffered response to the client
		flush_interval -1
		header_up X-Real-IP {remote_host}
	}
}
```

My authelia config

```yaml
      - id: gotosocial
        description: GotoSocial
        secret: 'secret'
        authorization_policy: two_factor
        consent_mode: auto
        redirect_uris:
          - https://social.example.net/auth/callback
        scopes:
          - openid
          - profile
          - groups
          - email
        userinfo_signing_algorithm: none
```

My gotosocial config

```yaml
#######################
##### OIDC CONFIG #####
#######################
oidc-enabled: true

oidc-idp-name: "Cyberendroit"

oidc-skip-verification: false

oidc-issuer: "https://auth.cyberendroit.net"

oidc-client-id: "gotosocial"

oidc-client-secret: 'secret'

oidc-scopes:
  - "openid"
  - "email"
  - "profile"
  - "groups"

oidc-link-existing: false

oidc-allowed-groups: ["premium"]

oidc-admin-groups: ["admin"]
```
