### ISSUE TITLE
[bug] Split-domain 不能登录 phanpy.social 和 neodb.social

### ISSUE THREAD

**Issue by rebron1900** [superseriousbusiness/gotosocial#2824]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

I'm having problems trying to log into phanpy.social and neodb.social after installing gotosocial using docker.

my gotosocial config file

```yaml
host: "gts.1900.live"
account-domain: "1900.live"

db-type: "sqlite"
db-address: "/gotosocial/storage/sqlite.db"

instance-languages: "zh"

TZ: "Asia/Shanghai"

storage-backend: "s3"
storage-s3-endpoint: ""
storage-s3-proxy: false
storage-s3-access-key: ""
storage-s3-secret-key: ""
storage-s3-bucket: ""

letsencrypt-enabled: false
```

my docker-compose file
```yaml
version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1003:1003
    environment:
      GTS_CONFIG_PATH: /gotosocial/config.yaml
    ports:
      - "25257:8080"

    volumes:
      - /home/rebron1900/data/gts-data:/gotosocial/storage  
      - type: bind
        source: /home/rebron1900/data/gts-data/config.yaml
        target: /gotosocial/config.yaml
        read_only: true
    restart: "always"
```

Currently the Reverse proxy should be successful, accessing `https://1900.live/.well-known/webfinger?resource=acct:@1900@gts.1900.live` and `https://gts.1900.live/.well- known/webfinger?resource=acct:@1900@gts.1900.live` both get the data.

The current situation is as follows
1. phanpy.social can be logged in using the host domain, but not the account domain. 2.
2. neodb.social can't login with both host domain and account domain.

neodb.social error info of account-domain `Example 1900.live returns an error, code: 404`

neodb.social error info of host-domain
```
Bad Request: application for client_id 01D5AV31Q3H05XJ2R39WET6B4X could not be retrieved: If you arrived at this error during a sign in/oauth flow, please try clearing your session cookies and signing in again; if problems persist, make sure you're using the correct credentials
```

### What's your GoToSocial Version?

 GoToSocial 0.15.0-SNAPSHOT+git-6db7d01 🦥

### Browser version

Chrome 123.0.6312.107
