### ISSUE TITLE
[bug] error executing command: error creating dbservice: sqlite ping: unable to open database file: out of memory

### ISSUE THREAD

**Issue by sunwoo1524** [superseriousbusiness/gotosocial#3030]
### Describe the bug with a clear and concise description of what the bug is.

error executing command: error creating dbservice: sqlite ping: unable to open database file: out of memory

### What's your GoToSocial Version?

v0.16.0

### What happened?

I was installing gotosocial with docker compose following the official documentation.
But The gotosocial instance is not working with this error:
> gotosocial  | 2024/06/22 14:31:00 error executing command: error creating dbservice: sqlite ping: unable to open database file: out of memory (14) (code=14)

**Comment by tsmethurst** [comment]
The error message suggests something funky with your system or database file. What kind of environment are you running in? Did you change anything in the dockerfile? Does the container have valid permissions to read + write whatever you've mounted into it?

**Comment by sunwoo1524** [comment]
I didn't change the Dockerfile.
Mounted directory have 755 permisions, but it doesn't have a sqlite database file.
My docker-compose.yml is:
```
version: "3.3"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    environment:
      GTS_HOST: (my domain)
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      ## For reverse proxy setups:
      # GTS_TRUSTED_PROXIES: "172.x.x.x"
      ## Set the timezone of your server:
      TZ: Asia/Seoul
    ports:
      - "8041:8080"
      ## For letsencrypt:
      #- "80:80"
      ## For reverse proxy setups:
      #- "127.0.0.1:8080:8080"
    volumes:
      - ./data:/gotosocial/storage
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default   
```
