### ISSUE TITLE
[bug] Cannot follow other instances, federated timeline is missing, always return 401 unauthenticated

### ISSUE THREAD

**Issue by Ashpex** [superseriousbusiness/gotosocial#3581]
### Describe the bug with a clear and concise description of what the bug is.

Whenever I follow an account on another Mastodon instance, even if the target account is open to follow, it results in a follow request on my end. Also the federated instance is missing toots. 

I checked the log and it shows 401 unauthenticated :

```go
timestamp="28/11/2024 07:04:21.070" func=workers.(*Processor).ProcessFromClientAPI level=INFO activityType=Create objectType=Follow fromAccount=ashpex msg="processing from client API"
timestamp="28/11/2024 07:04:21.070" func=server.init.func1.Logger.13.1 level=INFO latency="1.911963ms" userAgent="Mozilla/5.0 (Android 14; Mobile; rv:132.0) Gecko/132.0 Firefox/132.0" method=POST statusCode=200 path=/api/v1/accounts/01JDN7PQ3YC7J6SFN03SZJ3D6K/follow clientIP=2001:ee0:4f4c:1530:9f96:8316:be9:6521 requestID=sgzhaw4k04001vfn80ag msg="OK: wrote 177B"
timestamp="28/11/2024 07:04:21.071" func=federation.(*federatingActor).Send level=INFO msg="send activity Follow via outbox https://social.ashpex.net/users/ashpex/outbox"
timestamp="28/11/2024 07:04:21.524" func=httpclient.(*Client).DoOnce level=INFO method=POST url=https://fosstodon.org/inbox contentType="application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"" attempt="1" pubKeyID=https://social.ashpex.net/users/ashpex/main-key msg="401 Unauthorized"
```

Here is my docker compose file:

```yaml
services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
      #user: 1000:1000
    networks:
      - gotosocial
    environment:
      GTS_HOST: social.ashpex.net 
      GTS_ACCOUNT_DOMAIN: ashpex.net
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_WAZERO_COMPILATION_CACHE: /gotosocial/.cache
      GTS_LANDING_PAGE_USER: "ashpex"
      GTS_TRUSTED_PROXIES: "172.29.0.1"
    ports:
      - "9999:8080"
    volumes:
      - ./data/storage:/gotosocial/storage
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
```

I am using Cloudflare Tunnel if that helps, and this is my instance: https://social.ashpex.net/

Thank you!

### What's your GoToSocial Version?

0.17.3+git-6f4cb2f

### GoToSocial Arch

amd64 docker image
