### ISSUE TITLE
[bug] Docker-compose results in sqlite error

### ISSUE THREAD

**Issue by khanzf** [superseriousbusiness/gotosocial#3704]
### Describe the bug with a clear and concise description of what the bug is.

Through docker compose, I am having the container crash due to this error:
```
gotosocial  | timestamp="28/01/2025 21:42:07.792" func=workers.(*Workers).Stop level=INFO msg="stopped scheduler"
gotosocial  | timestamp="28/01/2025 21:42:07.792" func=workers.(*Workers).Stop level=INFO msg="stopped delivery workers"
gotosocial  | timestamp="28/01/2025 21:42:07.792" func=workers.(*Workers).Stop level=INFO msg="stopped client workers"
gotosocial  | timestamp="28/01/2025 21:42:07.793" func=workers.(*Workers).Stop level=INFO msg="stopped federator workers"
gotosocial  | timestamp="28/01/2025 21:42:07.793" func=workers.(*Workers).Stop level=INFO msg="stopped dereference workers"
gotosocial  | timestamp="28/01/2025 21:42:07.793" func=workers.(*Workers).Stop level=INFO msg="stopped processing workers"
gotosocial  | timestamp="28/01/2025 21:42:07.793" func=server.init.func1.1 level=INFO msg="done! exiting..."
gotosocial  | 2025/01/28 21:42:07 error executing command: error creating dbservice: sqlite ping: sqlite3: unable to open database file (code=14 extended=14)
gotosocial exited with code 0
```

My docker-compose.yml is as follows:

```
services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    environment:
      # Change this to your actual host value.
      GTS_HOST: gotosocial.EXAMPLE.INSTANCE
      GTS_DB_TYPE: sqlite
      # Path in the GtS Docker container where
      # the sqlite.db file will be stored.
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      # Change this to true if you're not running
      # GoToSocial behind a reverse proxy.
      GTS_LETSENCRYPT_ENABLED: "false"
      # Set your email address here if you
      # want to receive letsencrypt notices.
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      # Path in the GtS Docker container where the
      # Wazero compilation cache will be stored.
      GTS_WAZERO_COMPILATION_CACHE: /gotosocial/.cache
      ## For reverse proxy setups:
      GTS_TRUSTED_PROXIES: "172.18.0.1/16"
      ## Set the timezone of your server:
      TZ: America/New_York
    ports:
      - "443:8080"
      ## For letsencrypt:
      #- "80:80"
      ## For reverse proxy setups:
      #- "127.0.0.1:8080:8080"
    volumes:
      # Your data volume, for your
      # sqlite.db file and media files.
      - ~/gotosocial/data:/gotosocial/storage
      # OPTIONAL: To mount volume for the WAZERO
      # compilation cache, for speedier restart
      # times, uncomment the below line:
      #- ~/gotosocial/.cache:/gotosocial/.cache
    restart: "always"

networks:
  gotosocial:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"

```

I do not know which version this is, since I am setting the version to "latest".

### What's your GoToSocial Version?

latest

### GoToSocial Arch

x64 Docker

### What happened?

I am running `docker compose up` and receiving a sqlite error followed by a crash.

### What you expected to happen?

I expect the server to start running.

### How to reproduce it?

Please use my docker-compose.yml file above, and run `docker compose up` to reproduce the same result.

### Anything else we need to know?

This is my first time running Gotosocial.
