### ISSUE TITLE
Cannot Login with any client

### ISSUE THREAD

**Issue by avks** [superseriousbusiness/gotosocial#3802]
### Describe the bug with a clear and concise description of what the bug is.

I cannot login to GTS instance from any client. So far I tried elk, moshidon, phanpy

### What's your GoToSocial Version?

GoToSocial 0.18.0-rc2+git-1ee56d6

### What happened?

Installed GTS with docker. Created new user from backend and elevated to admin. Tried logging in from a elk. Took me to authorization page. After authorization, elk throws up: `ERROR: TypeError: NetworkError when attempting to fetch resource.` I have looked into the console and found multiple errors saying: `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://domain.tld/api/v1/preferences. (Reason: CORS request did not succeed). Status code: (null).`

### What you expected to happen?

Clients should log in after being authorized

### Anything else we need to know?

I am running GTS with docker. Here's the `docker-compose.yml`:
```
services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: 1000:1000
    networks:
      - gotosocial
    environment:
      # Change this to your actual host value.
      GTS_HOST: domain.tld
      GTS_DB_TYPE: sqlite
      # Path in the GtS Docker container where
      # the sqlite.db file will be stored.
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      # Change this to true if you're not running
      # GoToSocial behind a reverse proxy.
      #GTS_LETSENCRYPT_ENABLED: "false"
      # Set your email address here if you
      # want to receive letsencrypt notices.
      #GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
      # Path in the GtS Docker container where the
      # Wazero compilation cache will be stored.
      GTS_WAZERO_COMPILATION_CACHE: /gotosocial/.cache
      ## For reverse proxy setups:
      #GTS_TRUSTED_PROXIES: "172.18.0.1/16"
      ## Set the timezone of your server:
      TZ: "Asia/Calcutta"
      GTS_TRUSTED_PROXIES: "172.18.0.1/16,127.0.0.1/32,::1"
    ports:
      - "8080:8080"
      ## For letsencrypt:
      #- "80:80"
      ## For reverse proxy setups:
      #- "127.0.0.1:8080:8080"
    volumes:
      # Your data volume, for your
      # sqlite.db file and media files.
      - ./data:/gotosocial/storage
      # OPTIONAL: To mount volume for the WAZERO
      # compilation cache, for speedier restart
      # times, uncomment the below line:
      - ./.cache:/gotosocial/.cache
    restart: "always"


networks:
  gotosocial:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/16"
          gateway: "172.18.0.1"
```
