### ISSUE TITLE
[bug/frontend] Downloadable font is Latin‐only

### ISSUE THREAD

**Issue by flashymittens** [superseriousbusiness/gotosocial#3995]
### Describe the bug with a clear and concise description of what the bug is. Please include screenshots of any visual issues.

Latin and non‐Latin text use different fonts.

### What's your GoToSocial Version?

3.5.3+0.18.3+git-b6e56fe

### Browser version

128.9.0esr

### What happened?

Posts that use mixed scripts use different fonts.

### What you expected to happen?

The font is the same (whenever possible).

### How to reproduce it?

Open a page with mixed scripts. Example:

> Lorem ipsum dolor sit amet…
> <span lang="cv">Эпӗ кунта пурӑнатӑп…</span>

### Anything else we need to know?

Noto Sans is big, so embedding its full version is, probably, undesirable. Alternatively, consider (optionally?) not embedding fonts for normal text at all (Fork-Awesome for icons is fine; or a battle for another day…):

1) Set a font (or fonts), but not embed it:

```css
html { font-family: "Noto Sans", system-ui, sans-serif; }
```

2) Always use default system or browser font:

```css
html { font-family: system-ui, sans-serif; }
```

or

```css
html { font-family: sans-serif; }
```
