### ISSUE TITLE
[feature] Make the rate-limit configurable

### ISSUE THREAD

**Issue by zladuric** [superseriousbusiness/gotosocial#943]
### Is your feature request related to a problem ?

It would be great if we had a way to configure rate-limits via environment or config or CLI flags.

I host my own gotosocial instance and my own pinafore instance for several weeks now. In the last two weeks, I've fully migrated my mastodon account to my instance and have in that time ran into the rate-limit (429 API responses) 3 times already. It's not a big inconvenience, but it does count, and I would like to play with the limits - probably by increasing the sliding window size and the accompanying limits accordingly - that way it would support my bursty activity (read the timeline, open a bunch of new windows, do things I want done all in a short period of time, then be inactive for hours again).

### Describe the solution you'd like.

I run GTS in docker and use the provided docker-compose, ideally I would like these settings to be exposed via environment variables.

### Describe alternatives you've considered.

NONE

The only page in the docs where this is mentioned is this page: https://docs.gotosocial.org/en/latest/api/swagger/ and it doesn't explain that the limits are fixed, or if they're not, how to change them.

**Comment by NyaaaWhatsUpDoc** [comment]
This was already the plan, and fortunately simple to do, so we'll bump it up the priority list :)

**Comment by tsmethurst** [comment]
Heya, if you've run into the rate limit 3 times already it sounds like either your reverse proxy might not be configured properly to forward the client IP header to GoToSocial, or GoToSocial is not configured properly to trust the forward proxy. In your logs, do all client IPs show as the same address?

**Comment by zladuric** [comment]
I'll have to check the logs but probably yes. As I've said, I'm the sole user anyway. But my usage pattern is in bursts - when I caught the error, I've monitored (manually) the header and saw that I can make a hundred request quite easily. Scroll the timeline, open a few toots and profiles in a new tab, that gets me to high numbers pretty quickly.

In any case, I'll look into logs and the whole situation a bit more carefully, for now I just wanted to know if I'm missing something regarding rate limit configuration. And the previous comment answered that already.

**Comment by i5heu** [comment]
I also experienced this issue as the only user on my instance and IP forwarding.

**Comment by tsmethurst** [comment]
> i have this error because I host behind Cloudflare and I cannot whitelist these IPs

If that's the case, you should be able to list the cloudflare IP CIDR right? Then I think it will work, since your GtS will trust x-forwarded-for headers from cloudflare

**Comment by i5heu** [comment]
https://chaos.social/web/@margio@infosec.exchange/109291177623796752

some ppl complaining that they run into the limit.
I have GTS running behind Traefik which should transport the IP (I have no errors) - also my dashboard looks just normal 

![Bildschirm­foto 2022-11-05 um 13 48 06](https://user-images.githubusercontent.com/22565269/200120610-bb07a47a-ee0b-4784-b9ff-63c6d8700830.png)

**Comment by tsmethurst** [comment]
> I have GTS running behind Traefik which should transport the IP

Did you set up your [trusted-proxies](https://github.com/superseriousbusiness/gotosocial/blob/main/example/config.yaml#L93) to point to the IP address of traefik (both ipv6 and ipv4)? In your GtS logs, do client IPs on requests always show as the same IP address?

**Comment by i5heu** [comment]
so I have no quick access to the logs nor the config file, but since the 172.* is not default I would assume it also limits Traefik

**Comment by tsmethurst** [comment]
Indeed :) You'll need to add the CIDR or just the IP for traefik to your trusted-proxies, then you should no longer run into this rate limiting issue *unless* someone actually does make 1000 requests to your instance within 5 minutes :P

**Comment by i5heu** [comment]
> You'll need to add the CIDR or just the IP for traefik to your trusted-proxies

is this possible over a env variable?


here is my docker-compose.yml for reference

```yml
version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    environment:
      - INFLUXDB_UDP_ENABLED=true
      - INFLUXDB_UDP_DATABASE=traefik
    command:
      #- "--api.insecure=true"
      - "--metrics.influxDB2=true"
      - "--metrics.influxDB2.address=http://XXXXXX:8086"
      - "--metrics.influxDB2.token=XXXXXXXXXX=="
      - "--metrics.influxDB2.org=org"
      - "--metrics.influxDB2.bucket=data"
      - "--metrics.influxDB2.addentrypointslabels=true"
      - "--metrics.influxDB2.addserviceslabels=true"
      - "--metrics.influxDB2.addRoutersLabels=true"
      - "--metrics.influxDB2.pushinterval=1s"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=XXXXXX"
      - "--certificatesresolvers.le.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--log.level=DEBUG"
      # - "--certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "always"
  influxdb:
    image: influxdb:2.4-alpine
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=XXXXXXX
      - DOCKER_INFLUXDB_INIT_PASSWORD=XXXXXXX
      - DOCKER_INFLUXDB_INIT_BUCKET=data
      - DOCKER_INFLUXDB_INIT_ORG=org
    ports:
      - "8086:8086"
    volumes:
      - "./influxdb2:/var/lib/influxdb2"
  gotosocial:
    image: superseriousbusiness/gotosocial:0.5.2
    container_name: gotosocial
    user: 1000:1000
    environment:
      GTS_HOST: miau.pub
      GTS_DB_TYPE: sqlite
      GTS_DB_ADDRESS: /gotosocial/storage/sqlite.db
      GTS_LETSENCRYPT_ENABLED: "false"
      GTS_LETSENCRYPT_EMAIL_ADDRESS: ""
    volumes:
      - ./gotosocial/data:/gotosocial/storage
    restart: "always"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gotosocial.loadbalancer.server.port=8080"
      - "traefik.http.routers.gotosocial.rule=Host(`miau.pub`)"
      - "traefik.http.routers.gotosocial.tls=true"
      - "traefik.http.routers.gotosocial.tls.certresolver=le"
networks:
  default:
    external:
      name: webproxy
```
